from __future__ import annotations

from sqlalchemy import Boolean, Column, DateTime, Float, ForeignKey, Index, Integer, LargeBinary, MetaData, String, Table, Text, UniqueConstraint

metadata = MetaData()
PREFIX = "res_ai_v2_"

schema_migrations = Table(PREFIX + "schema_migrations", metadata, Column("version", Integer, primary_key=True), Column("description", Text, nullable=False), Column("applied_at", DateTime(timezone=True), nullable=False))
settings = Table(PREFIX + "settings", metadata, Column("key", String(120), primary_key=True), Column("value", Text, nullable=False), Column("updated_at", DateTime(timezone=True), nullable=False))
executor_structure = Table(PREFIX + "executor_structure", metadata, Column("id", Integer, primary_key=True), Column("res_name", Text, nullable=False, unique=True), Column("branch_name", Text, nullable=False), Column("active", Boolean, nullable=False, default=True), Column("created_at", DateTime(timezone=True), nullable=False), Column("updated_at", DateTime(timezone=True), nullable=False))
source_files = Table(PREFIX + "source_files", metadata, Column("id", Integer, primary_key=True), Column("file_hash", String(64), nullable=False, unique=True), Column("file_name", Text, nullable=False), Column("source_kind", String(32), nullable=False), Column("row_count", Integer, nullable=False, default=0), Column("imported_rows", Integer, nullable=False, default=0), Column("status", String(24), nullable=False, default="imported"), Column("imported_at", DateTime(timezone=True), nullable=False))
source_rows = Table(PREFIX + "source_rows", metadata, Column("id", Integer, primary_key=True), Column("source_file_id", Integer, ForeignKey(source_files.c.id), nullable=False, index=True), Column("sheet_name", Text, nullable=False, default=""), Column("row_number", Integer, nullable=False), Column("raw_json", Text, nullable=False), Column("raw_hash", String(64), nullable=False, index=True), Column("canonical_hash", String(64), nullable=False, index=True), Column("created_at", DateTime(timezone=True), nullable=False), UniqueConstraint("source_file_id", "sheet_name", "row_number", name=PREFIX + "uq_source_position"))
addresses = Table(PREFIX + "addresses", metadata, Column("id", Integer, primary_key=True), Column("address_key", String(64), nullable=False, unique=True, index=True), Column("locality", Text, nullable=False, default=""), Column("district", Text, nullable=False, default=""), Column("settlement", Text, nullable=False, default=""), Column("street", Text, nullable=False, default=""), Column("locality_key", Text, nullable=False, default="", index=True), Column("district_key", Text, nullable=False, default="", index=True), Column("settlement_key", Text, nullable=False, default="", index=True), Column("street_key", Text, nullable=False, default="", index=True), Column("created_at", DateTime(timezone=True), nullable=False), Column("updated_at", DateTime(timezone=True), nullable=False))
Index(PREFIX + "ix_address_anchor", addresses.c.locality_key, addresses.c.settlement_key, addresses.c.district_key)
address_aliases = Table(PREFIX + "address_aliases", metadata, Column("id", Integer, primary_key=True), Column("address_id", Integer, ForeignKey(addresses.c.id), nullable=False, index=True), Column("entity_type", String(24), nullable=False), Column("alias_text", Text, nullable=False), Column("alias_key", Text, nullable=False, index=True), Column("verification", String(24), nullable=False, default="source_only"), Column("created_at", DateTime(timezone=True), nullable=False), UniqueConstraint("address_id", "entity_type", "alias_key", name=PREFIX + "uq_alias"))
address_mappings = Table(PREFIX + "address_mappings", metadata, Column("id", Integer, primary_key=True), Column("address_id", Integer, ForeignKey(addresses.c.id), nullable=False, index=True), Column("res_name", Text, nullable=False, index=True), Column("branch_name", Text, nullable=False), Column("status", String(24), nullable=False, default="source_only", index=True), Column("source_confidence", Float, nullable=False, default=80.0), Column("human_confirmations", Integer, nullable=False, default=0), Column("active", Boolean, nullable=False, default=True), Column("created_at", DateTime(timezone=True), nullable=False), Column("updated_at", DateTime(timezone=True), nullable=False), UniqueConstraint("address_id", "res_name", name=PREFIX + "uq_address_res"))
mapping_evidence = Table(PREFIX + "mapping_evidence", metadata, Column("id", Integer, primary_key=True), Column("mapping_id", Integer, ForeignKey(address_mappings.c.id), nullable=False, index=True), Column("source_row_id", Integer, ForeignKey(source_rows.c.id), nullable=True, index=True), Column("evidence_type", String(32), nullable=False), Column("evidence_key", String(64), nullable=False), Column("weight", Float, nullable=False, default=1.0), Column("created_at", DateTime(timezone=True), nullable=False), UniqueConstraint("mapping_id", "evidence_key", name=PREFIX + "uq_mapping_evidence"))
text_examples = Table(PREFIX + "text_examples", metadata, Column("id", Integer, primary_key=True), Column("example_hash", String(64), nullable=False, unique=True), Column("source_row_id", Integer, ForeignKey(source_rows.c.id), nullable=True, index=True), Column("raw_text", Text, nullable=False), Column("normalized_text", Text, nullable=False, index=True), Column("address_id", Integer, ForeignKey(addresses.c.id), nullable=True, index=True), Column("res_name", Text, nullable=False), Column("branch_name", Text, nullable=False), Column("status", String(24), nullable=False, default="source_only", index=True), Column("human_confirmations", Integer, nullable=False, default=0), Column("weight", Float, nullable=False, default=1.0), Column("created_at", DateTime(timezone=True), nullable=False), Column("updated_at", DateTime(timezone=True), nullable=False))
query_rules = Table(PREFIX + "query_rules", metadata, Column("id", Integer, primary_key=True), Column("normalized_query", Text, nullable=False, unique=True), Column("raw_query", Text, nullable=False), Column("selection_json", Text, nullable=False), Column("created_by", Text, nullable=False), Column("created_at", DateTime(timezone=True), nullable=False), Column("updated_at", DateTime(timezone=True), nullable=False))
review_tasks = Table(PREFIX + "review_tasks", metadata, Column("id", Integer, primary_key=True), Column("task_key", String(64), nullable=False, unique=True, index=True), Column("task_type", String(40), nullable=False, index=True), Column("subject_type", String(32), nullable=False), Column("subject_key", String(128), nullable=False, index=True), Column("title", Text, nullable=False), Column("payload_json", Text, nullable=False), Column("priority", Integer, nullable=False, default=0, index=True), Column("status", String(20), nullable=False, default="open", index=True), Column("created_at", DateTime(timezone=True), nullable=False), Column("updated_at", DateTime(timezone=True), nullable=False))
review_votes = Table(PREFIX + "review_votes", metadata, Column("id", Integer, primary_key=True), Column("task_id", Integer, ForeignKey(review_tasks.c.id), nullable=False, index=True), Column("reviewer", Text, nullable=False), Column("selection_json", Text, nullable=False), Column("is_admin", Boolean, nullable=False, default=False), Column("created_at", DateTime(timezone=True), nullable=False), UniqueConstraint("task_id", "reviewer", name=PREFIX + "uq_task_reviewer"))
review_decisions = Table(PREFIX + "review_decisions", metadata, Column("id", Integer, primary_key=True), Column("task_id", Integer, ForeignKey(review_tasks.c.id), nullable=False, index=True), Column("selection_json", Text, nullable=False), Column("applied_by", Text, nullable=False), Column("before_json", Text, nullable=False), Column("after_json", Text, nullable=False), Column("active", Boolean, nullable=False, default=True), Column("created_at", DateTime(timezone=True), nullable=False), Column("reversed_at", DateTime(timezone=True), nullable=True))
model_versions = Table(PREFIX + "model_versions", metadata, Column("id", Integer, primary_key=True), Column("version", String(64), nullable=False, unique=True, index=True), Column("status", String(20), nullable=False, index=True), Column("algorithm", String(80), nullable=False), Column("training_signature", String(64), nullable=False), Column("metrics_json", Text, nullable=False), Column("confusion_json", Text, nullable=False), Column("model_blob", LargeBinary, nullable=False), Column("gate_passed", Boolean, nullable=False, default=False), Column("created_at", DateTime(timezone=True), nullable=False), Column("published_at", DateTime(timezone=True), nullable=True))
prediction_events = Table(PREFIX + "prediction_events", metadata, Column("id", Integer, primary_key=True), Column("query_text", Text, nullable=False), Column("normalized_query", Text, nullable=False, index=True), Column("result_json", Text, nullable=False), Column("confidence", Float, nullable=False, default=0.0), Column("decision_status", String(24), nullable=False), Column("model_version", String(64), nullable=True), Column("created_at", DateTime(timezone=True), nullable=False))
audit_events = Table(PREFIX + "audit_events", metadata, Column("id", Integer, primary_key=True), Column("actor", Text, nullable=False), Column("action", String(64), nullable=False, index=True), Column("entity_type", String(40), nullable=False), Column("entity_key", Text, nullable=False), Column("before_json", Text, nullable=False, default="{}"), Column("after_json", Text, nullable=False, default="{}"), Column("created_at", DateTime(timezone=True), nullable=False))
